// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockCardiologia.Data;

#nullable disable

namespace StockCardiologia.Migrations
{
    [DbContext(typeof(DepositoContext))]
    [Migration("20230508032226_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("StockCardiologia.Models.Deposito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreDeposito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Deposito");
                });

            modelBuilder.Entity("StockCardiologia.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepositoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaProd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NSerie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Planilla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Remito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepositoId");

                    b.ToTable("Equipo");
                });

            modelBuilder.Entity("StockCardiologia.Models.Equipo", b =>
                {
                    b.HasOne("StockCardiologia.Models.Deposito", "Deposito")
                        .WithMany("Equipos")
                        .HasForeignKey("DepositoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposito");
                });

            modelBuilder.Entity("StockCardiologia.Models.Deposito", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
